################################################################################
# This is template for appveyor.yml
# Before using it in your repository, modify places marked with # TODO Modify
################################################################################

#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 1.0.{build}.0 # TODO Modify version
install:
    - git clone https://github.com/PowerShell/DscResource.Tests
    - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
    - ps: Invoke-AppveyorInstallTask

#---------------------------------# 
#      build configuration        # 
#---------------------------------# 

build: false

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask -CodeCoverage -CodeCovIo
    
#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 

# scripts to run before deployment 
deploy_script:
    - ps: |
        Invoke-AppveyorAfterTestTask
